### ISSUE TITLE
Google Maps API Key not functioning

### ISSUE THREAD

**Issue by andrewtat** [getexposure/exposure-android#5]
It doesn't seem like the Google Maps API Key is working due to some permissions error in the Google Maps API Console

**Comment by andrewtat** [comment]
Google Maps API Key is tied to @moychal's SHA fingerprint

**Comment by andrewtat** [comment]
APK required for multiple API Key usage. Tabling until beta release is finished

**Comment by moychal** [comment]
Issue fixed, need custom debug.keystore file in user's android directory.  Info on main readme.
